apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-containers
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init
  template:
    metadata:
      labels:
        app: init

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

      initContainers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"